qutebrowser: Fixed qute-1pass-wayland script

diff --git a/qutebrowser/userscripts/qute-1pass-wayland b/qutebrowser/userscripts/qute-1pass-wayland
--- a/qutebrowser/userscripts/qute-1pass-wayland
+++ b/qutebrowser/userscripts/qute-1pass-wayland
@@ -65,13 +65,12 @@ EOF
 URL=$(echo "$QUTE_URL" | awk -F/ '{print $3}' | sed 's/www.//g')
 TOKEN_TMPDIR="${TMPDIR:-/tmp}"
 TOKEN_CACHE="$TOKEN_TMPDIR/1pass.token"
-TITLE_JQ_EXPR='.title + " (in vault \"" + .vault.name + "\")"'
 
 dmenu-prompt() {
     local PROMPT="$1"
 
     if [[ -n "$QUTE_1PASS_DMENU_PROMPT" ]]; then
-        exec $QUTE_1PASS_DMENU_PROMPT "$PROMPT"
+        $QUTE_1PASS_DMENU_PROMPT "$PROMPT"
         return
     fi
 
@@ -86,8 +85,8 @@ dmenu-prompt() {
 dmenu-prompt-pass() {
     local PROMPT="$1"
 
-    if [[ -n "$QUTE_1PASS_DMENU_PASS_PROMPT" ]]; then
-        exec $QUTE_1PASS_DMENU_PASS_PROMPT "$PROMPT"
+    if [[ -n "$QUTE_1PASS_DMENU_PROMPT_PASS" ]]; then
+        $QUTE_1PASS_DMENU_PROMPT_PASS "$PROMPT"
         return
     fi
 
@@ -101,7 +100,7 @@ dmenu-prompt-pass() {
 
 clipboard-copy() {
     if [[ -n "$QUTE_1PASS_CLIPBOARD" ]]; then
-        exec $QUTE_1PASS_CLIPBOARD
+        $QUTE_1PASS_CLIPBOARD
         return
     fi
 
@@ -113,54 +112,36 @@ clipboard-copy() {
     xclip -in -selection clipboard
 }
 
-op-major-version() {
-    op --version | grep --only-matching '^[0-9]'
-}
+if ! command -v op > /dev/null; then
+    echo "message-error 'Missing required command-line tool: op'" >> "$QUTE_FIFO"
+    exit 1
+fi
 
-op-signin() {
-    if [[ "$OP_MAJOR_VERSION" == 1 ]]; then
-        op signin --output=raw "$@"
-        return
-    fi
-    op signin --raw "$@"
-}
+if ! command -v jq > /dev/null; then
+    echo "message-error 'Missing required command-line tool: jq'" >> "$QUTE_FIFO"
+    exit 1
+fi
 
-op-list() {
-    if [[ "$OP_MAJOR_VERSION" == 1 ]]; then
-        op list items --cache --session="$TOKEN"
-        return
-    fi
-    op item list --cache --session="$TOKEN" --format=json
-}
+OP_VERSION="$(op --version)"
+OP_MAJOR_VERSION="$(echo "$OP_VERSION" | grep --only-matching '^[0-9]')"
 
-op-get() {
-    if [[ "$OP_MAJOR_VERSION" == 1 ]]; then
-        op get item --cache --session="$TOKEN" "$@"
-        return
-    fi
-    op item get --cache --session="$TOKEN" --format=json "$@"
-}
-
-op-totp() {
-    if [[ "$OP_MAJOR_VERSION" == 1 ]]; then
-        op get totp --cache --session="$TOKEN"
-        return
-    fi
-    op item get --cache --session="$TOKEN" --otp "$@"
-}
+if [[ "$OP_MAJOR_VERSION" -lt 2 ]]; then
+    echo "message-error 'Requires op CLI v2.0.0 or higher, but got: $OP_VERSION'" >> "$QUTE_FIFO"
+    exit 1
+fi
 
 echo "message-info 'Looking for password for $URL...'" >> "$QUTE_FIFO"
 
-OP_MAJOR_VERSION="$(op-major-version)"
+JQ_TITLE_EXPR='.title + " (in vault \"" + .vault.name + "\")"'
 
 if [ -f "$TOKEN_CACHE" ]; then
     TOKEN="$(cat "$TOKEN_CACHE")"
-    if ! op-signin --session="$TOKEN" > /dev/null; then
-        TOKEN="$(dmenu-prompt-pass "1password: "| op-signin)" || TOKEN=""
+    if ! op signin --raw --session="$TOKEN" > /dev/null; then
+        TOKEN="$(dmenu-prompt-pass "1password: "| op signin --raw)" || TOKEN=""
         echo "$TOKEN" > "$TOKEN_CACHE"
     fi
 else
-    TOKEN=$(dmenu-prompt-pass "1password: "| op-signin) || TOKEN=""
+    TOKEN=$(dmenu-prompt-pass "1password: "| op signin --raw) || TOKEN=""
     install -m 600 /dev/null "$TOKEN_CACHE"
     echo "$TOKEN" > "$TOKEN_CACHE"
 fi
@@ -168,13 +149,12 @@ fi
 
 if [[ -z "$TOKEN" ]]; then
     echo "message-error 'Wrong master password'" >> "$QUTE_FIFO"
-    exit 0
+    exit 1
 fi
 
-LIST_ITEM_OUT="$(op-list)"
-if [[ $? != 0 ]]; then
-    echo "message-error 'Failed to list items. See :process for more info'" >> "$QUTE_FIFO"
-    exit 0
+if ! LIST_ITEM_OUT="$(op item list --cache --session="$TOKEN" --format=json)"; then
+    echo "message-error 'Failed to list items.'" >> "$QUTE_FIFO"
+    exit 1
 fi
 
 MATCHING_ITEMS="$(echo "$LIST_ITEM_OUT" | jq --arg url "$URL" '[.[] | select((.urls//[])[].href | test($url))]')"
@@ -183,21 +163,21 @@ MATCHING_COUNT="$(echo "$MATCHING_ITEMS" | jq -r 'length')"
 UUID=""
 if [[ "$MATCHING_COUNT" == 1 ]]; then
     UUID="$(echo "$MATCHING_ITEMS" | jq -r '.[0].id')"
-    TITLE="$(echo "$MATCHING_ITEMS" | jq -r '.[0] | '"$TITLE_JQ_EXPR")"
+    TITLE="$(echo "$MATCHING_ITEMS" | jq -r '.[0] | '"$JQ_TITLE_EXPR")"
     echo "message-info 'Found 1 entry for $URL: $TITLE'" >> "$QUTE_FIFO"
-elif [[ "$MATCHING_COUNT" > 1 ]]; then
+elif [[ "$MATCHING_COUNT" -gt 1 ]]; then
     echo "message-info 'Found $MATCHING_COUNT entries for $URL'" >> "$QUTE_FIFO"
-    TITLE="$(echo "$MATCHING_ITEMS" | jq -r '.[] | '"$TITLE_JQ_EXPR" | dmenu-prompt)" || TITLE=""
+    TITLE="$(echo "$MATCHING_ITEMS" | jq -r '.[] | '"$JQ_TITLE_EXPR" | dmenu-prompt "Select item for $URL")" || TITLE=""
     if [ -n "$TITLE" ]; then
-        UUID=$(echo "$MATCHING_ITEMS" | jq --arg title "$TITLE" -r '[.[] | select('"$TITLE_JQ_EXPR"' | test($title)).id] | first // ""') || UUID=""
+        UUID=$(echo "$MATCHING_ITEMS" | jq --arg title "$TITLE" -r '[.[] | select('"$JQ_TITLE_EXPR"' == $title).id] | first // ""') || UUID=""
     else
         UUID=""
     fi
 else
     echo "message-error 'No entry found for $URL'" >> "$QUTE_FIFO"
-    TITLE="$(echo "$LIST_ITEM_OUT" | jq -r '.[] | '"$TITLE_JQ_EXPR" | dmenu-prompt)" || TITLE=""
+    TITLE="$(echo "$LIST_ITEM_OUT" | jq -r '.[] | '"$JQ_TITLE_EXPR" | dmenu-prompt)" || TITLE=""
     if [ -n "$TITLE" ]; then
-        UUID=$(echo "$LIST_ITEM_OUT" | jq --arg title "$TITLE" -r '[.[] | select('"$TITLE_JQ_EXPR"' | test($title)).id] | first // ""') || UUID=""
+        UUID=$(echo "$LIST_ITEM_OUT" | jq --arg title "$TITLE" -r '[.[] | select('"$JQ_TITLE_EXPR"' == $title).id] | first // ""') || UUID=""
     else
         UUID=""
     fi
@@ -205,17 +185,17 @@ fi
 
 if [[ -z "$UUID" ]];then
     echo "message-error 'No item picked.'" >> "$QUTE_FIFO"
-    exit 0
+    exit 1
 fi
 
-ITEM="$(op-get "$UUID")"
+ITEM="$(op item get --cache --session="$TOKEN" --format=json "$UUID")"
 
-TITLE="$(echo "$ITEM" | jq -r "$TITLE_JQ_EXPR")"
+TITLE="$(echo "$ITEM" | jq -r "$JQ_TITLE_EXPR")"
 PASSWORD="$(echo "$ITEM" | jq -r '[.fields[] | select(.purpose=="PASSWORD") | .value] | first // ""')"
 
 if [ -z "$PASSWORD" ]; then
     echo "message-error 'No password found in $TITLE'" >> "$QUTE_FIFO"
-    exit 0
+    exit 1
 fi
 
 USERNAME="$(echo "$ITEM" | jq -r '[.fields[] | select(.purpose=="USERNAME") | .value] | first // ""')"
@@ -224,8 +204,9 @@ printjs() {
     js | sed 's,//.*$,,' | tr '\n' ' '
 }
 echo "jseval -q $(printjs)" >> "$QUTE_FIFO"
+echo "message-info 'Using credentials from: $TITLE'" >> "$QUTE_FIFO" 
 
-TOTP="$(echo "$ITEM" | op-totp "$UUID")" || TOTP=""
+TOTP="$(echo "$ITEM" | op item get --cache --session="$TOKEN" --otp "$UUID")" || TOTP=""
 if [ -n "$TOTP" ]; then
     echo "$TOTP" | clipboard-copy
     echo "message-info 'Pasted one time password for $TITLE to clipboard'" >> "$QUTE_FIFO" 
